#!/usr/bin/env python3

'''
Script to run authentication user
'''

import os
import sys

try:
    import pexpect
except ImportError:
    print('Required library "pexpect" not exists. Install with pip and try again')
    sys.exit(1)

# Define command to request new token
_COMMAND_ = './cliente.py "%(proxy)s"'

# Message used by authentication client when asking for a password
_PASSWORD_MESSAGE_ = 'Enter password:'
_TIMEOUT_FOR_MESSAGE_ = 15

# Get required arguments
try:
    user, password, proxy = sys.argv[1:]
except ValueError:
    print('Command arguments: {} <user> <password> <proxy>'.format(
        os.path.basename(sys.argv[0]))
    )
    sys.exit(1)


# Run command
old_pwd=os.getcwd()
os.chdir("icegauntlet_auth_server")
proc = pexpect.spawn(_COMMAND_%{"proxy": proxy}, echo=False)
os.chdir(old_pwd)

found = proc.expect(["opcion"])
if found == 0:
    proc.sendline('2')
else:
    print('ERROR: opcion no encontrada')
    sys.exit(1)

found = proc.expect(["user"])
if found == 0:
    proc.sendline(user)
else:
    print('ERROR: usuario no encontrado')
    sys.exit(1)

found = proc.expect(["password"])
if found == 0:
    proc.sendline(password)
else:
    print('ERROR: password no encontrada')
    sys.exit(1)

proc.expect([pexpect.EOF])
# Show command output and exit
print(proc.before.decode().strip())
sys.exit(0)
